import * as React from "react"
import {
  previewImports,
  availablePreviews,
} from "./__generated__/preview-imports"

/**
 * Returns a miniature, non-interactive preview element for a component.
 *
 * Auto-discovered from components/docs/previews/<slug>.tsx.
 * Import map is generated by scripts/generate-preview-imports.ts.
 *
 * To add a preview for a new registry item:
 * 1. Create components/docs/previews/<registry-name>.tsx
 * 2. Run `pnpm previews:generate`
 */
export async function getCardPreview(
  slug: string
): Promise<React.ReactNode | null> {
  if (!availablePreviews.has(slug) || !previewImports[slug]) return null

  const mod = await previewImports[slug]()
  const Preview = mod.default
  return <Preview />
}
