/**
 * Generates registry/__index__.tsx from registry.json.
 *
 * This creates a component lookup map so ComponentPreview can render
 * components by name in MDX files. Runs alongside `shadcn build`.
 *
 * Run: tsx scripts/build-registry-index.ts
 */

import { readFileSync, writeFileSync, readdirSync, existsSync } from "node:fs"
import { join, basename } from "node:path"

const ROOT = process.cwd()
const REGISTRY_JSON = join(ROOT, "registry.json")
const OUTPUT = join(ROOT, "registry/__index__.tsx")

interface RegistryItem {
  name: string
  type: string
  files: { path: string; type: string }[]
}

const registry = JSON.parse(readFileSync(REGISTRY_JSON, "utf-8"))
const items: RegistryItem[] = registry.items

// Discover example files from registry/<name>/examples/
function discoverExamples(): RegistryItem[] {
  const examples: RegistryItem[] = []
  const registryDir = join(ROOT, "registry")

  for (const dir of readdirSync(registryDir, { withFileTypes: true })) {
    if (!dir.isDirectory()) continue
    const examplesDir = join(registryDir, dir.name, "examples")
    if (!existsSync(examplesDir)) continue

    for (const file of readdirSync(examplesDir)) {
      if (!file.endsWith(".tsx")) continue
      const name = basename(file, ".tsx")
      examples.push({
        name,
        type: "registry:example",
        files: [{
          path: `registry/${dir.name}/examples/${file}`,
          type: "registry:example",
        }],
      })
    }
  }

  return examples
}

const examples = discoverExamples()

let index = `// @ts-nocheck
// Auto-generated by scripts/build-registry-index.ts
// Do not edit manually.
import * as React from "react"

// biome-ignore lint: autogenerated file
export const Index: Record<string, any> = {`

const allItems = [...items, ...examples]

for (const item of allItems) {
  if (!item.files?.length) continue

  const mainFile = item.files[0]
  const importPath = `@/${mainFile.path.replace(/\.tsx?$/, "")}`

  index += `
  "${item.name}": {
    name: "${item.name}",
    type: "${item.type}",
    files: ${JSON.stringify(
      item.files.map((f) => ({
        path: f.path,
        type: f.type,
        target: "",
      }))
    )},
    component: React.lazy(async () => {
      const mod = await import("${importPath}")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "${item.name}"
      return { default: mod.default || mod[exportName] }
    }),
  },`
}

index += `
}
`

writeFileSync(OUTPUT, index)
console.log(`✓ Generated registry index for ${items.length} items + ${examples.length} examples → registry/__index__.tsx`)
