/**
 * Generates registry/__index__.tsx from registry.json.
 *
 * This creates a component lookup map so ComponentPreview can render
 * components by name in MDX files. Runs alongside `shadcn build`.
 *
 * Run: tsx scripts/build-registry-index.ts
 */

import { readFileSync, writeFileSync } from "node:fs"
import { join } from "node:path"

const ROOT = process.cwd()
const REGISTRY_JSON = join(ROOT, "registry.json")
const OUTPUT = join(ROOT, "registry/__index__.tsx")

interface RegistryItem {
  name: string
  type: string
  files: { path: string; type: string }[]
}

const registry = JSON.parse(readFileSync(REGISTRY_JSON, "utf-8"))
const items: RegistryItem[] = registry.items

let index = `// @ts-nocheck
// Auto-generated by scripts/build-registry-index.ts
// Do not edit manually.
import * as React from "react"

// biome-ignore lint: autogenerated file
export const Index: Record<string, any> = {`

for (const item of items) {
  if (!item.files?.length) continue

  const mainFile = item.files[0]
  const importPath = `@/${mainFile.path.replace(/\.tsx?$/, "")}`

  index += `
  "${item.name}": {
    name: "${item.name}",
    type: "${item.type}",
    files: ${JSON.stringify(
      item.files.map((f) => ({
        path: f.path,
        type: f.type,
        target: "",
      }))
    )},
    component: React.lazy(async () => {
      const mod = await import("${importPath}")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "${item.name}"
      return { default: mod.default || mod[exportName] }
    }),
  },`
}

index += `
}
`

writeFileSync(OUTPUT, index)
console.log(`✓ Generated registry index for ${items.length} items → registry/__index__.tsx`)
