/**
 * Scans components/docs/previews/ and generates the import map
 * for the component catalog card previews.
 *
 * Run: npx tsx scripts/generate-preview-imports.ts
 * Hooked into: dev, build scripts via "previews:generate"
 */

import { readdirSync, writeFileSync } from "node:fs"
import { join, basename } from "node:path"

const PREVIEWS_DIR = join(process.cwd(), "components/docs/previews")
const OUTPUT_FILE = join(
  process.cwd(),
  "components/docs/__generated__/preview-imports.ts"
)

const slugs = readdirSync(PREVIEWS_DIR)
  .filter((f) => f.endsWith(".tsx"))
  .map((f) => basename(f, ".tsx"))
  .sort()

const lines = [
  "// Auto-generated by scripts/generate-preview-imports.ts",
  "// Do not edit manually. Run `pnpm previews:generate` to update.",
  "",
  'import type { ComponentType } from "react"',
  "",
  "export const previewImports: Record<",
  "  string,",
  "  () => Promise<{ default: ComponentType }>",
  "> = {",
  ...slugs.map(
    (slug) => `  "${slug}": () => import("../previews/${slug}"),`
  ),
  "}",
  "",
  `export const availablePreviews = new Set(${JSON.stringify(slugs)})`,
  "",
]

// Ensure output dir exists
const outputDir = join(process.cwd(), "components/docs/__generated__")
import { mkdirSync } from "node:fs"
mkdirSync(outputDir, { recursive: true })

writeFileSync(OUTPUT_FILE, lines.join("\n"))

console.log(
  `✓ Generated preview imports for ${slugs.length} components → ${OUTPUT_FILE.replace(process.cwd() + "/", "")}`
)
